server:
    port: 80
    

spring:
    datasource:
        write:
            username: root
            password: root
            jdbc-url: jdbc:mysql://localhost:3306/yinlihu?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
            driver-class-name: com.mysql.jdbc.Driver
        read:
            username: root
            password: root
            jdbc-url: jdbc:mysql://localhost:3306/yinlihu2?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
            driver-class-name: com.mysql.jdbc.Driver
        
mybatis-plus:
    type-aliases-package: club.yinlihu.entity
    global-config:
        refresh-mapper: true